http:
  middlewares:
    custom-auth:
      basicAuth:
        users:
          - admin:$apr1$hhZ0Uzlv$H64Wk4NY0CTJ3oj72nfs70 # htpasswd -nb user password
          - admin:$apr1$hhZ0Uzlv$H64Wk4NY0CTJ3oj72nfs70 # htpasswd -nb user password
  services:
    portainer-service:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"  
          
  routers:
    traefik:
      entryPoints:
        - websecure
      service: api@internal
      rule: Host("traefik.test.domain.com")
      # middlewares:
      #   - custom-auth
      tls:
        certresolver: cloudflare
        domains: 
          - main: "*.test.domain.com"
            sans: 
              - "*.test.domain.com"

    portainer-router:
      rule: "Host(`admin.test.domain.com`)"  
      service: portainer-service
      # middlewares:
      #   - custom-auth
      tls:
        certresolver: cloudflare
        domains: 
          - main: "*.test.domain.com"
            sans: 
              - "*.test.domain.com"

  


  